name: ERT-straight

on:
  push:
  pull_request:
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab
  schedule:
    - cron: '0 0 * * *' # daily

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - 29.2
          - 29.3
          - 29.4
          - release-snapshot
          - snapshot
    steps:
      # - name: Set up Emacs
      #   uses: purcell/setup-emacs@master
      #   with:
      #     version: ${{ matrix.emacs_version }}

      # Checks-out repository under $GITHUB_WORKSPACE
      - name: Clone verilog-ext
        uses: actions/checkout@v4
        with:
          submodules: true

      # INFO: Temporary until tree-sitter 0.25 makes it into nixpkgs
      - name: Set up Emacs 29.4
        run: |
          test/test-hdl/scripts/install-tree-sitter.sh
          test/test-hdl/scripts/install-emacs.sh

      - name: Install binaries
        run: |
          test/test-hdl/scripts/verilog/setup-env.sh
          test/test-hdl/scripts/verilog/install-ts-grammar.sh

      - name: Run ERT tests
        run: |
          make
