name: elisp-check

on:
  pull_request:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        emacs_version:
          - 29.1
          - release-snapshot
        elisp-check:
          - melpa

    steps:
      - name: Clone verilog-ext
        uses: actions/checkout@v4

      - name: Set up Emacs
        uses: purcell/setup-emacs@master
        with:
          version: ${{ matrix.emacs_version }}

      - name: elisp-checks
        uses: leotaku/elisp-check@master
        with:
          check: ${{ matrix.elisp-check }}
          file: verilog-ext.el

